name: Test workflow
on:
  workflow_dispatch:

jobs:
  First_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: run a linux command
        run: |
          echo "Hello World!"
          echo $HOME
          echo $SHELL
          echo $USER
          echo $PATH
          !/bin/bash

          # Define the target IP address
          TARGET_IP="8.8.8.8"  # Replace with your actual target IP

          # Perform continuous ping for 10 times
          PING_COUNT=10
          ping_result=$(ping -c $PING_COUNT $TARGET_IP)

          # Extract packet loss percentage
          packet_loss=$(echo "$ping_result" | grep -oP '\d+(?=% packet loss)')

          # Check if packet loss percentage is less than 10%
          if [ "$packet_loss" -lt 10 ]; then
              echo "Closing the case: Packet loss is within acceptable limits. Packet loss: **$packet_loss%**"
          elif [ "$packet_loss" -eq 100 ]; then
              echo "Assigning to NOC team: High packet loss detected (100%)."
          else
              echo "Assigning to NOC team: High packet loss detected. Packet loss: **$packet_loss%**"
          fi

          # Exception handling
          if [ $? -ne 0 ]; then
              echo "Error: Ping command failed. Please check network connectivity."
          fi